'use strict';
// Synthetic scores are test-only, never a runtime fallback.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const C=require('../core.js');const root=path.join(__dirname,'..');
test('histogram uses precise half-open 0.10-second bins, not rounded display values, and excludes DNF',()=>{assert.equal(typeof C.histogram,'function');const h=C.histogram([600,609,609.9,610,619,619.9,620,null].map(score=>({score})));assert.deepEqual(h.bins.map(b=>[b.label,b.count]),[['6.00–6.09',3],['6.10–6.19',3],['6.20–6.29',1]]);assert.equal(h.valid,7);assert.equal(h.dnf,1);assert.equal(h.bins[0].endExclusive,6.1);assert.equal(h.bins.reduce((s,b)=>s+b.count,0),h.valid);const binary=C.histogram([{score:8.2*100}]);assert.equal(binary.bins[0].label,'8.20–8.29');});
test('histogram includes empty neighboring bins and keeps extreme values without massive allocation',()=>{const h=C.histogram([{score:600},{score:620}]);assert.deepEqual(h.bins.map(b=>b.count),[1,0,1]);const large=C.histogram([{score:600},{score:999900}]);assert.equal(large.sparse,true);assert.equal(large.bins.length,2);assert.equal(large.bins.reduce((sum,b)=>sum+b.count,0),2);assert.equal(C.histogram([]).bins.length,0);assert.equal(C.histogram([{score:null},{score:null}]).dnf,2);});
function boot(){const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),els=new Map();const element=id=>({id,value:id==='range'?'0':'',attrs:{},listeners:{},textContent:'',innerHTML:'',classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=String(v)},removeAttribute(k){delete this.attrs[k]},addEventListener(k,f){(this.listeners[k]||=[]).push(f)},dispatch(k,event={}){for(const f of this.listeners[k]||[])f({target:this,...event})},focus(){},querySelector(){return null},scrollTo(){}});for(const m of html.matchAll(/\bid="([^"]+)"/g))els.set(m[1],element(m[1]));const get=id=>{assert.ok(els.has(id),'missing production DOM #'+id);return els.get(id)};const document=element('document');document.querySelector=s=>get(s.slice(1));document.visibilityState='visible';const record=(id,personId,score,date='2026-09-21')=>({id,personId,score,date,at:date+'T00:00:00Z',sourceRow:Number(id.replace(/\D/g,''))+2,sourceCell:'B2',note:''});let payload={data:{version:1,people:[{id:'p1',name:'Test A'},{id:'p2',name:'Test B'}],records:[...Array.from({length:125},(_,i)=>record('r'+i,'p1',600)),record('r125','p1',650,'2026-09-20'),record('r126','p1',null),record('r127','p2',710)],warnings:[],source:{title:'Test only'}},source:{title:'Test only'},lastSuccessAt:new Date().toISOString(),refreshing:false,stale:false,error:null};const sandbox={document,CubeStats:C,console,setInterval(){},setTimeout,fetch:async()=>({ok:true,status:200,json:async()=>payload})};sandbox.window=sandbox;vm.runInNewContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),sandbox);return {get,flush:async()=>{for(let i=0;i<12;i++)await Promise.resolve()},person(id){document.dispatch('click',{target:{closest:()=>({dataset:{person:id}})}})},replace(records){payload={...payload,data:{...payload.data,records}}}};}
const binCount=ui=>[...ui.get('chart').innerHTML.matchAll(/data-count="(\d+)"/g)].reduce((sum,m)=>sum+Number(m[1]),0);
test('complete histogram fits desktop and mobile widths with every tick visible in non-overlapping rows',async()=>{
 const ui=boot();await ui.flush();ui.get('histogram-chart-tab').dispatch('click');
 for(const width of [320,600,1200])for(const scores of [[600],[600,930],Array.from({length:160},(_,i)=>600+i*10),[600,999900]]){
  ui.get('chart').clientWidth=width;
  const records=scores.map((score,i)=>({id:'tick'+i,personId:'p1',score,date:'2026-09-21',sourceRow:i+2,note:''}));
  ui.replace(records);ui.get('refresh-data').dispatch('click');await ui.flush();
  const svg=ui.get('chart').innerHTML,bins=C.histogram(records).bins;
  const ticks=[...svg.matchAll(/<text class="distribution-tick" data-tick="(\d+)" data-tick-row="(\d+)" x="([\d.]+)" y="([\d.]+)"[^>]*>(.*?)<\/text>/g)];
  assert.equal(ticks.length,bins.length,'no interval label may be skipped');
  const viewBox=/viewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(svg);assert.equal(Number(viewBox[1]),width-16,'SVG uses only the available width');
  const rows=new Map();ticks.forEach((tick,i)=>{assert.equal(Number(tick[1]),bins[i].index);assert.ok(tick[5].includes('>'+bins[i].start.toFixed(1)+'</tspan>'));assert.ok(tick[5].includes(bins[i].label),'full range remains in the title');const x=Number(tick[3]),y=Number(tick[4]),labelWidth=bins[i].start.toFixed(1).length*8;assert.ok(x-labelWidth/2>=0&&x+labelWidth/2<=Number(viewBox[1]),'label stays inside plot');assert.ok(y+4<Number(viewBox[2]),'last row is not clipped');const previous=rows.get(tick[2]);if(previous)assert.ok(x-previous.x>=(labelWidth+previous.width)/2+10-1e-8,'same-row labels do not overlap');rows.set(tick[2],{x,width:labelWidth});});
  const bars=[...svg.matchAll(/<rect data-bin="\d+" data-count="\d+" x="([\d.]+)"[^>]*width="([\d.]+)"/g)];assert.equal(bars.length,bins.length);for(const bar of bars)assert.ok(Number(bar[1])>=0&&Number(bar[1])+Number(bar[2])<=width-16,'every bar fits');
  assert.doesNotMatch(svg,/rotate\(|min-width:/);assert.match(svg,/style="width:100%;height:\d+px"/);assert.equal(binCount(ui),scores.length);
 }
 const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');assert.match(css,/\.chart\.is-distribution\{[^}]*overflow:hidden/);assert.match(css,/\.distribution-tick\{font-size:14px/);
});
test('trend/distribution switch reuses one chart, counts all filtered records and preserves mode across people/refresh',async()=>{const ui=boot();await ui.flush();assert.equal(ui.get('trend-chart-tab').attrs['aria-pressed'],'true');ui.get('histogram-chart-tab').dispatch('click');assert.equal(ui.get('chart-title').textContent,'ao5 用时分布');assert.equal(ui.get('histogram-chart-tab').attrs['aria-pressed'],'true');assert.equal(binCount(ui),126,'histogram counts all valid records in the selected range');assert.match(ui.get('chart').innerHTML,/6\.00–6\.09/);assert.match(ui.get('chart').innerHTML,/DNF 1 组/);ui.get('range').value='day';ui.get('range').dispatch('change');assert.equal(binCount(ui),125,'specific day filters the histogram');ui.person('p2');assert.equal(binCount(ui),1);assert.match(ui.get('chart').innerHTML,/7\.10–7\.19/);ui.get('refresh-data').dispatch('click');await ui.flush();assert.equal(ui.get('histogram-chart-tab').attrs['aria-pressed'],'true');ui.get('trend-chart-tab').dispatch('click');assert.equal(ui.get('chart-title').textContent,'ao5 变化趋势');assert.match(ui.get('chart').innerHTML,/class="trend-line"/);assert.doesNotMatch(ui.get('chart').innerHTML,/<circle/);ui.get('histogram-chart-tab').dispatch('click');ui.replace([{id:'dnf',personId:'p2',score:null,date:'2026-09-21',at:'2026-09-21T00:00:00Z',sourceRow:2,note:''}]);ui.get('refresh-data').dispatch('click');await ui.flush();assert.match(ui.get('chart').innerHTML,/只有 DNF/);assert.equal(binCount(ui),0);});
