'use strict';
// Synthetic scores are test-only, never a runtime fallback.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const C=require('../core.js');const root=path.join(__dirname,'..');
test('histogram uses precise half-open 0.10-second bins, not rounded display values, and excludes DNF',()=>{assert.equal(typeof C.histogram,'function');const h=C.histogram([600,609,609.9,610,619,619.9,620,null].map(score=>({score})));assert.deepEqual(h.bins.map(b=>[b.label,b.count]),[['6.00–6.09',3],['6.10–6.19',3],['6.20–6.29',1]]);assert.equal(h.valid,7);assert.equal(h.dnf,1);assert.equal(h.bins[0].endExclusive,6.1);assert.equal(h.bins.reduce((s,b)=>s+b.count,0),h.valid);const binary=C.histogram([{score:8.2*100}]);assert.equal(binary.bins[0].label,'8.20–8.29');});
test('histogram includes empty neighboring bins and keeps extreme values without massive allocation',()=>{const h=C.histogram([{score:600},{score:620}]);assert.deepEqual(h.bins.map(b=>b.count),[1,0,1]);const large=C.histogram([{score:600},{score:999900}]);assert.equal(large.sparse,true);assert.equal(large.bins.length,2);assert.equal(large.bins.reduce((sum,b)=>sum+b.count,0),2);assert.equal(C.histogram([]).bins.length,0);assert.equal(C.histogram([{score:null},{score:null}]).dnf,2);});
function boot(){const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),els=new Map();const element=id=>({id,value:id==='range'?'0':'',attrs:{},listeners:{},textContent:'',innerHTML:'',classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=String(v)},removeAttribute(k){delete this.attrs[k]},addEventListener(k,f){(this.listeners[k]||=[]).push(f)},dispatch(k,event={}){for(const f of this.listeners[k]||[])f({target:this,...event})},focus(){},querySelector(){return null},scrollTo(){}});for(const m of html.matchAll(/\bid="([^"]+)"/g))els.set(m[1],element(m[1]));const get=id=>{assert.ok(els.has(id),'missing production DOM #'+id);return els.get(id)};const document=element('document');document.querySelector=s=>get(s.slice(1));document.visibilityState='visible';const record=(id,personId,score,date='2026-09-21')=>({id,personId,score,date,at:date+'T00:00:00Z',sourceRow:Number(id.replace(/\D/g,''))+2,sourceCell:'B2',note:''});let payload={data:{version:1,people:[{id:'p1',name:'Test A'},{id:'p2',name:'Test B'}],records:[...Array.from({length:125},(_,i)=>record('r'+i,'p1',600)),record('r125','p1',650,'2026-09-20'),record('r126','p1',null),record('r127','p2',710)],warnings:[],source:{title:'Test only'}},source:{title:'Test only'},lastSuccessAt:new Date().toISOString(),refreshing:false,stale:false,error:null};const sandbox={document,CubeStats:C,console,setInterval(){},setTimeout,fetch:async()=>({ok:true,status:200,json:async()=>payload})};sandbox.window=sandbox;vm.runInNewContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),sandbox);return {get,flush:async()=>{for(let i=0;i<12;i++)await Promise.resolve()},person(id){document.dispatch('click',{target:{closest:()=>({dataset:{person:id}})}})},replace(records){payload={...payload,data:{...payload.data,records}}}};}
const binCount=ui=>[...ui.get('chart').innerHTML.matchAll(/data-count="(\d+)"/g)].reduce((sum,m)=>sum+Number(m[1]),0);
test('complete histogram fits desktop and mobile widths with every tick visible in non-overlapping rows',async()=>{
 const ui=boot();await ui.flush();ui.get('histogram-chart-tab').dispatch('click');
 for(const width of [320,600,1200])for(const scores of [[600],[600,930],Array.from({length:160},(_,i)=>600+i*10),[600,999900]]){
  ui.get('chart').clientWidth=width;
  const records=scores.map((score,i)=>({id:'tick'+i,personId:'p1',score,date:'2026-09-21',sourceRow:i+2,note:''}));
  ui.replace(records);ui.get('refresh-data').dispatch('click');await ui.flush();
  const svg=ui.get('chart').innerHTML,bins=C.histogram(records).bins;
  const ticks=[...svg.matchAll(/<text class="distribution-tick" data-tick="(\d+)" data-tick-row="(\d+)" x="([\d.]+)" y="([\d.]+)"[^>]*>(.*?)<\/text>/g)];
  assert.equal(ticks.length,bins.length,'no interval label may be skipped');
  const viewBox=/viewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(svg);assert.equal(Number(viewBox[1]),width-16,'SVG uses only the available width');
  const rows=new Map();ticks.forEach((tick,i)=>{assert.equal(Number(tick[1]),bins[i].index);assert.ok(tick[5].includes('>'+bins[i].start.toFixed(1)+'</tspan>'));assert.ok(tick[5].includes(bins[i].label),'full range remains in the title');const x=Number(tick[3]),y=Number(tick[4]),labelWidth=bins[i].start.toFixed(1).length*8;assert.ok(x-labelWidth/2>=0&&x+labelWidth/2<=Number(viewBox[1]),'label stays inside plot');assert.ok(y+4<Number(viewBox[2]),'last row is not clipped');const previous=rows.get(tick[2]);if(previous)assert.ok(x-previous.x>=(labelWidth+previous.width)/2+10-1e-8,'same-row labels do not overlap');rows.set(tick[2],{x,width:labelWidth});});
  const bars=[...svg.matchAll(/<rect data-bin="\d+" data-count="\d+" x="([\d.]+)"[^>]*width="([\d.]+)"/g)];assert.equal(bars.length,bins.length);for(const bar of bars)assert.ok(Number(bar[1])>=0&&Number(bar[1])+Number(bar[2])<=width-16,'every bar fits');
  assert.doesNotMatch(svg,/rotate\(|min-width:/);assert.match(svg,/style="width:100%;height:\d+px"/);assert.equal(binCount(ui),scores.length);
 }
 const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');assert.match(css,/\.chart\.is-distribution\{[^}]*overflow:hidden/);assert.match(css,/\.distribution-tick\{font-size:14px/);
});
test('all nonempty bins keep their count labels, shifting collisions above bars and reserving header space',async()=>{
 const ui=boot();await ui.flush();ui.get('histogram-chart-tab').dispatch('click');
 for(const width of [320,600,1200])for(const counts of [[125],Array.from({length:34},(_,i)=>i%7===0?0:i%3===0?17:13),Array.from({length:160},()=>1),[1,120,2,99,12,9,100,1]]){
  ui.get('chart').clientWidth=width;let id=0;const records=counts.flatMap((count,i)=>Array.from({length:count},()=>({id:'count'+(++id),personId:'p1',score:600+i*10,date:'2026-09-21',sourceRow:id+2,note:''})));
  ui.replace(records);ui.get('refresh-data').dispatch('click');await ui.flush();const svg=ui.get('chart').innerHTML,bins=C.histogram(records).bins;
  const labels=[...svg.matchAll(/<text class="distribution-count" data-count-bin="(\d+)" x="([\d.]+)" y="([\d.]+)"[^>]*>(\d+)<\/text>/g)].map(m=>({bin:Number(m[1]),x:Number(m[2]),y:Number(m[3]),count:Number(m[4]),width:m[4].length*9}));
  assert.equal(labels.length,bins.filter(b=>b.count).length,'every nonempty bar has a label');assert.equal(labels.reduce((sum,l)=>sum+l.count,0),records.length);
  const bars=[...svg.matchAll(/<rect data-bin="(\d+)" data-count="(\d+)" x="([\d.]+)" y="([\d.]+)" width="([\d.]+)"/g)].map(m=>({bin:Number(m[1]),count:Number(m[2]),x:Number(m[3]),y:Number(m[4]),width:Number(m[5])}));
  for(const [i,l] of labels.entries()){
   const bar=bars.find(b=>b.bin===l.bin);assert.equal(l.count,bar.count);assert.ok(Math.abs(l.x-(bar.x+bar.width/2))<1e-8);assert.ok(l.y-14>=24,'does not overlap summary');assert.ok(l.x-l.width/2>=0&&l.x+l.width/2<=width-16,'no clipping');
   for(const other of labels.slice(0,i))assert.ok(Math.abs(l.x-other.x)>=(l.width+other.width)/2+4-1e-8||Math.abs(l.y-other.y)>=20,'count labels do not overlap');
   for(const b of bars)if(b.count&&l.x+l.width/2>b.x&&l.x-l.width/2<b.x+b.width)assert.ok(l.y<=b.y-7+1e-8,'labels stay above overlapping bars');
  }
 }
});
test('people share distribution frame, tick rows and empty-state height without sharing scores',async()=>{
 const ui=boot();await ui.flush();let id=0;const make=(personId,count,score,date='2026-09-21')=>Array.from({length:count},()=>({id:'align'+(++id),personId,score,date,sourceRow:id+2,note:''}));
 const records=[...make('p1',26,700),...Array.from({length:34},(_,i)=>make('p2',i%2?26:12,590+i*10)).flat(),...make('p1',1,500,'2026-09-20')];ui.replace(records);ui.get('refresh-data').dispatch('click');await ui.flush();
 const frame=()=>{const svg=ui.get('chart').innerHTML;return [...svg.match(/data-plot-top="([\d.]+)" data-plot-bottom="([\d.]+)" data-tick-rows="(\d+)" style="width:100%;height:(\d+)px"/)].slice(1).map(Number);};
 for(const width of [320,600,1200])for(const range of ['0','day']){
  ui.get('chart').clientWidth=width;ui.get('range').value=range;ui.get('range').dispatch('change');ui.get('histogram-chart-tab').dispatch('click');ui.person('p1');const first=frame();assert.equal(binCount(ui),range==='0'?27:26);
  ui.person('p2');assert.deepEqual(frame(),first,'plot and tick frame must not move on person switch');assert.equal(binCount(ui),646);ui.get('refresh-data').dispatch('click');await ui.flush();assert.deepEqual(frame(),first);
 }
 ui.replace(records.map(r=>r.personId==='p2'?{...r,score:null}:r));ui.get('refresh-data').dispatch('click');await ui.flush();const emptyHeight=Number(ui.get('chart').innerHTML.match(/style="height:(\d+)px/)[1]);assert.match(ui.get('chart').innerHTML,/只有 DNF/);assert.equal(binCount(ui),0);ui.person('p1');assert.equal(frame()[3],emptyHeight,'DNF view keeps the same reserved height');
});
test('browser: every distribution count remains visible without overlaps after desktop/mobile resizing', {skip:process.env.CUBE_UI_TEST!=='1',timeout:45000},async()=>{
 const {TencentReader}=require('../tencent-reader.cjs');const browser=new TencentReader();
 try{
  await browser.start();const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link rel="stylesheet"[^>]*>/,()=>'<style>'+fs.readFileSync(path.join(root,'styles.css'),'utf8')+'</style>');const frame=(await browser.cdp('Page.getFrameTree')).frameTree.frame.id;await browser.cdp('Page.setDocumentContent',{frameId:frame,html});
  let id=0;const records=Array.from({length:34},(_,i)=>Array.from({length:i%7===0?0:i%3===0?17:13},()=>({id:'count'+(++id),personId:'p1',score:600+i*10,date:'2026-09-21',sourceRow:id+2,note:''}))).flat();
  const extra=[...Array.from({length:125},(_,i)=>({id:'other'+i,personId:'p2',score:700,date:'2026-09-21',sourceRow:i+2,note:''})),{id:'dnf',personId:'p3',score:null,date:'2026-09-21',sourceRow:2,note:''},{id:'undated',personId:'p5',score:610,date:null,at:null,sourceRow:2,note:''}];
  const payload={data:{version:1,people:['p1','p2','p3','p4','p5'].map(id=>({id,name:id})),records:[...records,...extra],warnings:[]},lastSuccessAt:new Date().toISOString(),stale:false,error:null};await browser.evaluate(fs.readFileSync(path.join(root,'core.js'),'utf8'));await browser.evaluate(`window.fetch=async()=>({ok:true,status:200,json:async()=>(${JSON.stringify(payload)})})`);await browser.evaluate(fs.readFileSync(path.join(root,'app.js'),'utf8'));await browser.evaluate(`new Promise(r=>setTimeout(r,30))`);await browser.evaluate(`document.querySelector('#histogram-chart-tab').click()`);
  for(const width of [1366,1024,768,390,320]){
   await browser.cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<650});await browser.evaluate(`new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))`);
   const layout=await browser.evaluate(`(()=>{const svg=document.querySelector('.distribution-svg'),rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom}},bars=[...svg.querySelectorAll('rect[data-bin]')].filter(e=>Number(e.dataset.count)>0);return {svg:rect(svg),overflow:document.documentElement.scrollWidth>innerWidth,bars:bars.map(e=>({...rect(e),count:Number(e.dataset.count)})),labels:[...svg.querySelectorAll('.distribution-count')].map(e=>({...rect(e),count:Number(e.textContent)})),summary:rect(svg.querySelector('text'))}})()`);
   assert.equal(layout.overflow,false);assert.equal(layout.labels.length,layout.bars.length);assert.equal(layout.labels.reduce((s,l)=>s+l.count,0),records.length);
   const overlaps=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;
   for(const [i,l] of layout.labels.entries()){assert.ok(l.left>=layout.svg.left&&l.right<=layout.svg.right&&l.top>=layout.svg.top&&l.bottom<=layout.svg.bottom,width+'px label fits');assert.ok(!overlaps(l,layout.summary));for(const other of layout.labels.slice(0,i))assert.ok(!overlaps(l,other),width+'px no overlapping counts');for(const bar of layout.bars)assert.ok(!overlaps(l,bar),width+'px counts are not hidden inside bars');}
   const frame=()=>browser.evaluate(`(()=>{const svg=document.querySelector('.distribution-svg'),c=document.querySelector('#chart'),r=c.getBoundingClientRect();return {height:r.height,top:svg?Number(svg.dataset.plotTop):null,bottom:svg?Number(svg.dataset.plotBottom):null,ticks:svg?Number(svg.dataset.tickRows):null}})()`);
   const expected=await frame();await browser.evaluate(`document.querySelector('#people-list [data-person="p2"]').click()`);assert.deepEqual(await frame(),expected,width+'px fixed frame across different distributions');assert.equal(await browser.evaluate(`document.querySelector('.distribution-count').textContent`),'125');
   await browser.evaluate(`document.querySelector('#people-list [data-person="p3"]').click()`);assert.equal((await frame()).height,expected.height,width+'px empty state retains height');await browser.evaluate(`document.querySelector('#people-list [data-person="p1"]').click()`);
   const geometry=()=>browser.evaluate("(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,width:r.width,height:r.height}};return {chart:rect('#chart'),card:rect('.chart-card'),meta:rect('.chart-meta'),analysis:rect('.analysis-card'),row:rect('.overview-grid'),history:rect('.history-card'),overflow:document.documentElement.scrollWidth>innerWidth}})()");
   for(const range of ['0','empty-day']){
    await browser.evaluate("document.querySelector('#range').value="+JSON.stringify(range==='0'?'0':'day')+";document.querySelector('#range').dispatchEvent(new Event('change',{bubbles:true}));if("+JSON.stringify(range)+"==='empty-day'){document.querySelector('#range-date').value='2026-09-22';document.querySelector('#range-date').dispatchEvent(new Event('change',{bubbles:true}));}");
    for(const person of ['p1','p2','p3','p4','p5']){
     await browser.evaluate("document.querySelector('#people-list [data-person=\""+person+"\"]').click()");
     const anchor=await geometry();
     for(const mode of ['trend','histogram','trend','histogram']){
      await browser.evaluate("document.querySelector('#"+mode+"-chart-tab').click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
      const current=await geometry();assert.equal(current.overflow,false);
      for(const region of ['chart','card','meta','analysis','row','history'])for(const axis of ['top','bottom','height','left','width'])assert.ok(Math.abs(current[region][axis]-anchor[region][axis])<.01,width+'px '+person+'/'+range+' '+region+'.'+axis+' remains fixed when switching chart modes');
     }
    }
   }
   await browser.evaluate("document.querySelector('#range').value='0';document.querySelector('#range').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#people-list [data-person=\"p1\"]').click();document.querySelector('#histogram-chart-tab').click()");
   console.log(JSON.stringify({width,stableModeGeometry:true,scenarios:['dense','single-bin','DNF-only','empty','undated','empty-day']}));

  }
 }finally{await browser.close();}
});
test('trend/distribution switch reuses one chart, counts all filtered records and preserves mode across people/refresh',async()=>{const ui=boot();await ui.flush();assert.equal(ui.get('trend-chart-tab').attrs['aria-pressed'],'true');ui.get('histogram-chart-tab').dispatch('click');assert.equal(ui.get('chart-title').textContent,'ao5 用时分布');assert.equal(ui.get('histogram-chart-tab').attrs['aria-pressed'],'true');assert.equal(binCount(ui),126,'histogram counts all valid records in the selected range');assert.match(ui.get('chart').innerHTML,/6\.00–6\.09/);assert.match(ui.get('chart').innerHTML,/DNF 1 组/);ui.get('range').value='day';ui.get('range').dispatch('change');assert.equal(binCount(ui),125,'specific day filters the histogram');ui.person('p2');assert.equal(binCount(ui),1);assert.match(ui.get('chart').innerHTML,/7\.10–7\.19/);ui.get('refresh-data').dispatch('click');await ui.flush();assert.equal(ui.get('histogram-chart-tab').attrs['aria-pressed'],'true');ui.get('trend-chart-tab').dispatch('click');assert.equal(ui.get('chart-title').textContent,'日均 ao5 趋势');assert.match(ui.get('chart').innerHTML,/class="trend-line"/);assert.doesNotMatch(ui.get('chart').innerHTML,/<circle/);ui.get('histogram-chart-tab').dispatch('click');ui.replace([{id:'dnf',personId:'p2',score:null,date:'2026-09-21',at:'2026-09-21T00:00:00Z',sourceRow:2,note:''}]);ui.get('refresh-data').dispatch('click');await ui.flush();assert.match(ui.get('chart').innerHTML,/只有 DNF/);assert.equal(binCount(ui),0);});
