'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {publicPayload,assertSafe}=require('../publish.cjs');
const secret={url:'https://docs.qq.com/sheet/PRIVATE_DOCUMENT_123?tab=PRIVATE_TAB&rtkey=PRIVATE_KEY_123',sheetId:'PRIVATE_TAB'};
const raw={version:1,people:[{id:'PRIVATE_TAB_c2',name:'cy',sourceColumn:'B'}],records:[{id:'PRIVATE_TAB_r2_c2',personId:'PRIVATE_TAB_c2',score:699.9,date:'2026-09-30',at:'2026-09-29T16:00:00Z',sourceRow:2,sourceColumn:'B',sourceCell:'B2',sourceValue:6.999,sourceText:'6.999',note:''},{id:'PRIVATE_TAB_r3_c2',personId:'PRIVATE_TAB_c2',score:null,date:'2026-09-30',sourceRow:3,sourceColumn:'B',sourceCell:'B3',sourceValue:'DNF',sourceText:'DNF'}],warnings:[],source:secret};
test('publication whitelists fields, removes private source and IDs, retains precision and DNF',()=>{const p=publicPayload(raw,secret,'2026-09-30T12:00:00Z');assertSafe(JSON.stringify(p),secret);assert.equal(p.data.records.length,2);assert.equal(p.data.records[0].score,699.9);assert.equal(p.data.records[0].sourceText,'6.999');assert.equal(p.data.records[1].score,null);assert.equal(p.data.records[0].personId,p.data.people[0].id);assert.equal(p.data.source.url,undefined);assert.equal(p.lastSuccessAt,'2026-09-30T12:00:00Z');assert.equal(p.data.records[0].id,'r1');});
test('secrets anywhere in public output fail closed',()=>{for(const text of [secret.url,'PRIVATE_DOCUMENT_123','PRIVATE_TAB','PRIVATE_KEY_123','https://docs.qq.com/sheet/other','rtkey=another'])assert.throws(()=>assertSafe(text,secret));const poisoned=structuredClone(raw);poisoned.people[0].name=secret.url;assert.throws(()=>publicPayload(poisoned,secret));});
test('no records or invalid person references are never published',()=>{assert.throws(()=>publicPayload({...raw,records:[]},secret));assert.throws(()=>publicPayload({...raw,records:[{...raw.records[0],personId:'missing'}]},secret));});
test('static page uses relative GET only, no source link or API endpoint',()=>{const root=path.join(__dirname,'..');const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.doesNotMatch(app,/\/api\/|source\.url|method:manual|POST/);assert.match(app,/\.\/data\.json/);assert.doesNotMatch(html,/id="source-link"/);assert.match(html,/30 分钟/);});
